### ISSUE TITLE
It doesn't works after I click the image on the window UI.

### ISSUE THREAD

**Issue by yunfei920406** [momaabna/Segmenter#1]
1. When I click the image on the Widow UI, nothing appears. I don't know why?

2. The Window UI is so small and not very conveninet for use.

![image](https://user-images.githubusercontent.com/46222079/231340859-5f5d18dc-33f0-43d6-a1cd-6d5b206293ff.png)

**Comment by momaabna** [comment]
After selecting the class, you should click the start button to start the segmentation process in a new window. as an example, you can use the image from the examples folder.

**Comment by yunfei920406** [comment]
> After selecting the class, you should click the start button to start the segmentation process in a new window. as an example, you can use the image from the examples folder.

>Thanks for your response. I find the mistake is sourced from the wrong version of matplotlib. In my PC, I installed a new version of matplotlib.
